site_name: SPITE docs
site_url: http://docs.spiteful.ru
repo_url: https://github.com/likhachev-mischa/SPITE-Engine
repo_name: spite-engine
nav:
  - Overview: index.md
  - ECS Framework:
    - Overview: ecs.md

theme:
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      # accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/likhachev-mischa
      name: Engine Maintainer
    - icon: fontawesome/brands/github
      link: https://github.com/gpuslave
      name: Docs Maintainer
  generator: false